ues/counterparties/urls.py
from django.urls import path

from . import views


app_name = 'counterparties'

urlpatterns = [
    path(
        'contract_detail/<int:contract_id>/document_create/',
        views.add_document,
        name='add_document',
    ),
    path(
        'contract_detail/<int:contract_id>/document/<int:document_id>/delete/',
        views.delete_document,
        name='delete_document',
    ),
    path(
        '<int:counterparty_id>/contract_create/',
        views.contract_create,
        name='contract_create'
    ),
    path(
        '<int:counterparty_id>/contract_detail/<int:contract_id>/delete/',
        views.contract_delete,
        name='contract_delete'
    ),
    path(
        'contract_detail/<int:contract_id>/',
        views.contract_detail,
        name='contract_detail'
    ),
    path(
        'contract_detail/<int:contract_id>/edit/',
        views.contract_edit,
        name='contract_edit'
    ),
    path(
        'contracts_list/',
        views.contracts_list,
        name='contracts_list',
    ),
    path(
        'create/',
        views.counterparty_create,
        name='counterparty_create',
    ),
    path(
        '<int:counterparty_id>/delete/',
        views.counterparty_delete,
        name='counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/',
        views.counterparty_detail,
        name='counterparty_detail',
    ),
    path(
        '<int:counterparty_id>/edit/',
        views.counterparty_edit,
        name='counterparty_edit',
    ),
    path(
        'counterparties_list/',
        views.counterparties_list,
        name='counterparties_list'
    ),
    path(
        'contract_detail/<int:contract_id>/comments/create/',
        views.comment_create,
        name='comment_contract_create',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_contract_delete',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_contract_edit',
    ),
    path(
        '<int:counterparty_id>/comments/create/',
        views.comment_create,
        name='comment_counterparty_create',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_counterparty_edit',
    ),
]

ues/electricity_accounting/urls.py
from django.urls import path

from . import views
from counterparties import views as counterparties_views


app_name = 'accounting'

urlpatterns = [
    path(
        'point_detail/<int:point_id>/meter_create/',
        views.meter_create,
        name='meter_create',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/delete/',
        views.meter_delete,
        name='meter_delete',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/edit/',
        views.meter_edit,
        name='meter_edit',        
    ),
     path(
        'point_detail/<int:point_id>/transformer_create/',
        views.transformer_create,
        name='transformer_create',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/delete/',
        views.transformer_delete,
        name='transformer_delete',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/edit/',
        views.transformer_edit,
        name='transformer_edit',        
    ),
    path(
        'counterparties/contract_detail/<int:contract_id>/point_create/',
        views.point_create,
        name='point_create',
    ),
    path(
        'point_detail/<int:point_id>/',
        views.point_detail,
        name='point_detail',
    ),
    path(
        'point_detail/<int:point_id>/delete/',
        views.point_delete,
        name='point_delete',
    ),
    path(
        'point_detail/<int:point_id>/edit/',
        views.point_edit,
        name='point_edit',
    ),
    path(
        'points_list/',
        views.points_list,
        name='points_list',
    ),
    path(
        'tariff_create/',
        views.tariff_create,
        name='tariff_create',
    ),
    path(
        'tariffs/<int:tariff_id>/delete/',
        views.tariff_delete,
        name='tariff_delete',
    ),
    path(
        'tariffs/<int:tariff_id>/edit/',
        views.tariff_edit,
        name='tariff_edit',
    ),
    path(
        'tariffs_list/',
        views.tariffs_list,
        name='tariffs_list',
    ),
    path(
        'point_detail/<int:point_id>/calculations/add_calculation/',
        views.add_calculation,
        name='add_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/delete/',
        views.del_calculation,
        name='del_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/edit/',
        views.calculation_edit,
        name='calculation_edit',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/update/',
        views.calculation_tariff_update,
        name='calculation_tariff_update',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/download_xlsx_document/',
        views.download_xlsx_document,
        name='download_xlsx_document',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/create/',
        views.interconnection_create,
        name='interconnection_create',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/<int:interconnection_id>/delete/',
        views.interconnection_delete,
        name='interconnection_delete',
    ),
    path(
        'point_detail/<int:point_id>/document/create/',
        views.document_add,
        name='document_add',
    ),
    path(
        'point_detail/<int:point_id>/document/<int:document_id>/delete/',
        views.document_delete,
        name='document_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/create/',
        counterparties_views.comment_create,
        name='comment_point_create',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/delete/',
        counterparties_views.comment_delete,
        name='comment_point_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/edit/',
        counterparties_views.comment_edit,
        name='comment_point_edit',
    ),
    path(
        'static/<int:year>/',
        views.cumulative_statement_of_electricity_consumption,
        name='cumulative_statement_of_electricity_consumption',
    ),
    path(
        'static/<int:year>/download_xlsx_document_yearly_consumptions/',
        views.download_xlsx_document_yearly_consumptions,
        name='download_xlsx_document_yearly_consumptions',
    ),
]

ues/ues/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('accounting/', include('electricity_accounting.urls', namespace='accounting')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('', include('organization.urls', namespace='organization')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

ues/templates/accounting/includes/calculations_list.html
<!-- templates/accounting/includes/calculations_list.html -->
{% load static %}
{% load user_filters %}

<form id="main" method="post" action="{% url "accounting:add_calculation" point.id %}">
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th class="align-middle" scope="col" title="Номер счетчика">Номер счетчика</th>
      <th class="align-middle" scope="col" title="Дата внесения показаний">Дата</th>
      <th class="align-middle" scope="col" title="Показания счетчика электроэнергии">Показания</th>
      <th class="align-middle" scope="col" title="Разность показаний">Δ</th>
      <th class="align-middle" scope="col" title="Коэффициент трансформации">K</th>
      <th class="align-middle" scope="col" title="Количество кВт*ч">Количество</th>
      <th class="align-middle" scope="col" title="Вычет кВт*ч">Вычет</th>
      <th class="align-middle" scope="col" title="Потери в линиях, %">ΔP</th>
      <th class="align-middle" scope="col" title="Постоянные потери, кВт*ч">ΔS</th>
      <th class="align-middle" scope="col" title="Результат, кВт*ч">Σ</th>
      <th class="align-middle" scope="col" title="Тариф, руб./кВт*ч, Наценка, руб./кВ*ч">
        Тариф<br>
        Наценка
      </th>
      <th class="align-middle" scope="col" title="Начислено без НДС, руб., начислено c НДС, руб.">Начислено</th>
      {% if user.is_authenticated %}
        <th class="align-middle" scope="col"></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% if user.is_authenticated %}
      <tr id="add_readings">
        {% csrf_token %}
        <td class="align-middle">{{ current_meter_number }}</td>
        <td class="align-middle">{{ calculation_form.entry_date|addclass:"form-control" }}</td> 
        <td class="align-middle">{{ calculation_form.readings|addclass:"form-control" }}</td>
        <td class="align-middle">
          <input id="pr" type="hidden" value="{{previous_readings}}">
          <output id="dr">0</output>
        </td>
        <td class="align-middle">
          <output id="tc">{{ point.transformation_coefficient }}</output>
        </td>
        <td class="align-middle">
          <output id="amount" for="dr tc">0</output>
        </td>
        <td class="align-middle">
          <output id="deduction">{{ deductible_amount }}</output>
        </td>
        <td class="align-middle">
          <output id="losses">{{ point.losses }}</output>
        </td>
        <td class="align-middle">
          <output id="constant_losses">{{ point.constant_losses }}</output>
        </td>
        <td class="align-middle">
          <output id="result_amount" for="dr tc">0</output>
        </td>
        <td class="align-middle">
          {% if is_population %}
            <output id="tariff1">{{ tariff1 }}</output>
            <br>
            <output id="tariff2">{{ tariff2 }}</output>
            <br>
            <output id="tariff3">{{ tariff3 }}</output>
          {% else %}
            <output id="tariff1">{{ tariff1 }}</output>
            <output id="tariff2" class="d-none">{{ tariff2 }}</output>
            <output id="tariff3" class="d-none">{{ tariff3 }}</output>
          {% endif %}
          <br>
          <output id="margin">{{ point.margin }}</output>
        </td>

        <td class="align-middle">
          <output id="accrued" for="result_amount tariff1 tariff2 tariff3 margin">0</output>
          <br>
          <output id="accrued_NDS" for="accrued">0</output>
        </td>
        <td class="align-middle">
          <button type="submit" class="btn btn-link" title="Сохранить показания">
            <img src="{% static "icons/floppy.svg " %}" alt="Bootstrap" width="16" height="16">
          </button>
        </td> 
      </tr>
    {% endif %}
    {% for calculation in calculations %}
      <tr>
        <td class="align-middle">{{ calculation.meter }}</td>
        <td class="align-middle">{{ calculation.entry_date }}</td>
        <td class="align-middle">{{ calculation.readings }}</td>
        <td class="align-middle">{{ calculation.difference_readings }}</td>
        <td class="align-middle">{{ calculation.transformation_coefficient }}</td>
        <td class="align-middle">{{ calculation.amount }}</td>
        <td class="align-middle">{{ calculation.deductible_amount }}</td>
        <td class="align-middle">{{ calculation.losses }}</td>
        <td class="align-middle">{{ calculation.constant_losses }}</td>
        <td class="align-middle">{{ calculation.result_amount }}</td>
        <td class="align-middle">
          {% if calculation.tariff1 == calculation.tariff2%}
            {{ calculation.tariff1 }}
          {% else %}
            {{ calculation.tariff1 }}
            <br>
            {{ calculation.tariff2 }}
            <br>
            {{ calculation.tariff3 }}
          {% endif %}
            <br>
            {{ calculation.margin }}
        </td>
        <td class="align-middle">
          {{ calculation.accrued }}
          <br>
          {{ calculation.accrued_NDS }}
        </td>
        {% if user.is_authenticated %}
          <td class="align-middle">
            <a class="btn btn-link" href="{% url "accounting:download_xlsx_document" point.id calculation.id %}" title="Сохранить в формате xlsx">
              <img src="{% static "icons/filetype-xls.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
            <a class="btn btn-link" href="{% url "accounting:calculation_tariff_update" point.id calculation.id %}" title="Обновить тариф">
              <img src="{% static "icons/arrow-repeat.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
            <a class="btn btn-link" href="{% url "accounting:calculation_edit" point.id calculation.id %}" title="Редактировать">
              <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
            <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить показания от {{ calculation.entry_date }}?');" href="{% url 'accounting:del_calculation' point.id calculation.id %}" title="Удалить">
              <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>
</form>
<script src={% static "js/jquery-3.7.1.min.js" %}></script>
<script src={% static "js/readings_calculate.js" %}></script>

ues/templates/accounting/includes/comments.html
{% load comments %}
{% load static %}


{% if user.is_authenticated %}
  {% get_comment_form for point as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    <div class="input-group input-group-lg">
      <span class="input-group-text" id="inputGroup-sizing-lg" width="100%">
        <button type="submit" value="Add comment" id="id_submit" class="btn btn-link" title="Сохранить комментарий">
          <img src="{% static "icons/floppy.svg " %}" alt="Bootstrap" width="16" height="16">
        </button>
        {{ form.comment }}
      </span>
      
    </div>
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="next" value="{% url 'accounting:point_detail' point.id %}" />
  </form>
{% endif %}
{% get_comment_list for point as comment_list %}
{% for comment in comment_list %}
  <div class="card">
    <div class="card-body">
      <h6 class="card-title">{{ comment.user_name }}, {{ comment.submit_date|date:"d.m.Y H:i"  }}</h6>
      <p class="card-text">{{ comment.comment }}</p>
    </div>
  </div>
{% endfor %}
<link rel="stylesheet" href="{% static 'css/honeypot.css' %}">

ues/templates/accounting/includes/contract_points.html
<!-- templates/accounting/includes/contract_points.html -->
{% load user_filters %}

{% if points %}
  <table class="table caption-top table-striped table-hover table_sort">
    <caption>Всего точек учета: {{ points.count }}</caption>
    <thead class="table-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Наименование точки учёта</th>
        <th scope="col">Место расположения точки учета</th>
        <th scope="col">Источник питания</th>
        <th scope="col">Тип учёта</th>
      </tr>
    </thead>
    <tbody>
      {% for point in points %}
        <tr>
          <td scope="row"></td>
          <td>
            <a href="{% url 'accounting:point_detail' point.id %}">
              {{ point.name }}
            </a>
          </td>
          <td>{{ point.location }}</td>
          <td>{{ point.power_supply }}</td>
          <td>{{ point.get_type_of_accounting_display }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

ues/templates/accounting/includes/interconnection_list.html
<!-- templates/accounting/includes/interconnection_list.html -->

{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src={% static "js/table_sort.js" %}></script>

{% if user.is_authenticated %}
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <buttomn>
  </buttomn>
</div>
{% endif %}

{% if interconnected_lower_points %}
  <div>
    Точки учёта, чей объём потребленной электроэнергии вычитается из объёма электроэнрегии потреблённой данной точкой учёта
    <div class="container-fluid">
      <table class="table table-striped table-hover table_sort text-wrap">
        <thead class="table-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Контрагент</th>
            <th scope="col">Наименование точки учёта</th>
            <th scope="col">Место расположения точки учета</th>
            <th scope="col">Тип учёта</th>
            {% if user.is_authenticated %}
              <td class="align-middle"></td>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for interconnected_lower_point in interconnected_lower_points %}
            <tr>
              <td scope="row"></td>
              <td>
                <a href="{% url 'counterparties:counterparty_detail' interconnected_lower_point.lower_point.contract.counterparty.id %}">
                  {{ interconnected_lower_point.lower_point.contract.counterparty.short_name }}</td>
                </a>
              <td>
                <a href="{% url 'accounting:point_detail' interconnected_lower_point.lower_point.id %}">
                  {{ interconnected_lower_point.lower_point.name }}
                </a>
              </td>
              <td>{{ interconnected_lower_point.lower_point.location }}</td>
              <td>{{ interconnected_lower_point.lower_point.get_type_of_accounting_display }}</td>
              {% if user.is_authenticated %}
                <td class="align-middle">
                  <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить взаимосвязь?');" href="{% url 'accounting:interconnection_delete' point.id  interconnected_lower_point.id%}" title="Удалить">
                    <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endif %}
{% if interconnected_head_points %}
  <div>
    Точки учёта, из чьего объёма потребленной электроэнергии вычитается объём электроэнрегии, потреблённой данной точкой учёта
    <div class="container-fluid">
      <table class="table table-striped table-hover table_sort text-wrap">
        <thead class="table-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Контрагент</th>
            <th scope="col">Наименование точки учёта</th>
            <th scope="col">Место расположения точки учета</th>
            <th scope="col">Тип учёта</th>
            {% if user.is_authenticated %}
              <td class="align-middle"></td>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for interconnected_head_point in interconnected_head_points %}
            <tr>
              <td scope="row"></td>
              <td>
                <a href="{% url 'counterparties:counterparty_detail' interconnected_head_point.head_point.contract.counterparty.id %}">
                  {{ interconnected_head_point.head_point.contract.counterparty.short_name }}</td>
                </a>
              <td>
                <a href="{% url 'accounting:point_detail' interconnected_head_point.head_point.id %}">
                  {{ interconnected_head_point.head_point.name }}
                </a>
              </td>
              <td>{{ interconnected_head_point.head_point.location }}</td>
              <td>{{ interconnected_head_point.head_point.get_type_of_accounting_display }}</td>
              {% if user.is_authenticated %}
                <td class="align-middle">
                  <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить взаимосвязь?');" href="{% url 'accounting:interconnection_delete' point.id  interconnected_head_point.id%}" title="Удалить">
                    <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endif %}

ues/templates/accounting/includes/meters_list.html
<!-- templates/accounting/includes/meters_list.html -->
{% load thumbnail %}
{% load static %}

{% for meter in meters %}
  <div class="card mb-3" style="max-width: 50%;">
    <div class="row g-0">
      <div class="col-md-4">
        {% thumbnail meter.photo "200x200" crop="center" upscale=True as im %}
          <img class="img-thumbnail" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% empty %}
          <img class="img-thumbnail" src="{% static "icons/meter.png" %}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Счётчик электроэнергии</h5>
          <p class="card-text">
            <b>Марка:</b> {{ meter.mark }}</br>
            <b>Заводской номер:</b> {{ meter.number }}</br>
            <b>Дата установки:</b> {{ meter.installation_date }}</br>
            <b>Дата следующей поверки:</b> {{ meter.date_of_next_verification }}
          </p>
          <p class="card-text">
            <small class="text-body-secondary">Статус: действующий</small>
            {% if user.is_authenticated %}
              <a class="btn btn-link" href="{% url 'accounting:meter_edit' meter.point.id meter.id %}" title="Редактировать">
                <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
              </a>
              <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить счетчик э/э?');" href="{% url 'accounting:meter_delete' meter.point.id meter.id %}" title="Удалить">
                <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
              </a>
            {% endif %}
          </p>
          
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% if old_meters %}
  <p class="d-inline-flex gap-1">
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Демонтированные счётчики электроэнергии
    </button>
  </p>
{% endif %}
{% for old_meter in old_meters %}
  <div class="collapse" id="collapseExample">
    <div class="card mb-3" style="max-width: 50%;">
      <div class="row g-0">
        <div class="col-md-4">
          {% thumbnail old_meter.photo "200x200" crop="center" upscale=True as im %}
            <img class="img-thumbnail" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% empty %}
             <img class="img-thumbnail" src="{% static "icons/meter.png" %}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Счётчик электроэнергии</h5>
            <p class="card-text">
              <b>Марка:</b> {{ old_meter.mark }}</br>
              <b>Заводской номер:</b> {{ old_meter.number }}</br>
              <b>Дата установки:</b> {{ old_meter.installation_date }}</br>
              <b>Дата следующей поверки:</b> {{ old_meter.date_of_next_verification }}
            </p>
            <p class="card-text"></p>
            <p class="card-text">
              <small class="text-body-secondary">Статус: недействующий</small>
              {% if user.is_authenticated %}
                <a class="btn btn-link" href="{% url 'accounting:meter_edit' old_meter.point.id old_meter.id %}" title="Редактировать">
                  <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
                </a>
                <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить договор?');" href="{% url 'accounting:meter_delete' old_meter.point.id old_meter.id %}" title="Удалить">
                  <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                </a>
              {% endif %}
            </p> 
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

ues/templates/accounting/includes/point_documents.html
<!-- templates/accounting/includes/point_documents.html -->
{% load user_filters %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src="{% static 'js/table_sort.js' %}"></script>
<table class="table caption-top table-striped table-hover table_sort">
  <caption>Всего документов загружено: {{ documents_count }}</caption>
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование документа</th>
      <th scope="col">Дата подписания</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% if user.is_authenticated %}
      <form method="post" enctype="multipart/form-data" action="{% url 'accounting:document_add' point.id %}">
        {% csrf_token %}
        <tr>
          <td></td>
          <td>{{ document_form.title|addclass:"form-control" }}</td>
          <td>{{ document_form.conclusion_date|addclass:"form-control" }}</td>
          <td>{{ document_form.file|addclass:"form-control" }}</td>
          <td>
            <button type="submit" class="btn btn-link" title="Загрузить документ">
              <img src="{% static "icons/upload.svg " %}" alt="Bootstrap" width="16" height="16">
            </button>
          </td>
        </tr>
      </form>
    {% endif %}
    {% for document in documents %}
      <tr>
        <td scope="row"></td>
        <td>{{ document.title }}</td>
        <td>{{ document.conclusion_date }}</td>
        <td>
          <a class="btn btn-link" href="{{ document.file.url }}" title="Скачать документ" download>
            <img src="{% static "icons/download.svg " %}" alt="Bootstrap" width="16" height="16">
          </a>
        </td>
        {% if user.is_authenticated %}
          <td>
            <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить {{ document.title }}?');" href="{% url 'accounting:document_delete' point.id document.id %}" title="Удалить документ">
              <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>