ues/counterparties/urls.py
from django.urls import path

from . import views


app_name = 'counterparties'

urlpatterns = [
    path(
        'contract_detail/<int:contract_id>/document_create/',
        views.add_document,
        name='add_document',
    ),
    path(
        'contract_detail/<int:contract_id>/document/<int:document_id>/delete/',
        views.delete_document,
        name='delete_document',
    ),
    path(
        '<int:counterparty_id>/contract_create/',
        views.contract_create,
        name='contract_create'
    ),
    path(
        '<int:counterparty_id>/contract_detail/<int:contract_id>/delete/',
        views.contract_delete,
        name='contract_delete'
    ),
    path(
        'contract_detail/<int:contract_id>/',
        views.contract_detail,
        name='contract_detail'
    ),
    path(
        'contract_detail/<int:contract_id>/edit/',
        views.contract_edit,
        name='contract_edit'
    ),
    path(
        'contracts_list/',
        views.contracts_list,
        name='contracts_list',
    ),
    path(
        'create/',
        views.counterparty_create,
        name='counterparty_create',
    ),
    path(
        '<int:counterparty_id>/delete/',
        views.counterparty_delete,
        name='counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/',
        views.counterparty_detail,
        name='counterparty_detail',
    ),
    path(
        '<int:counterparty_id>/edit/',
        views.counterparty_edit,
        name='counterparty_edit',
    ),
    path(
        'counterparties_list/',
        views.counterparties_list,
        name='counterparties_list'
    ),
    path(
        'contract_detail/<int:contract_id>/comments/create/',
        views.comment_create,
        name='comment_contract_create',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_contract_delete',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_contract_edit',
    ),
    path(
        '<int:counterparty_id>/comments/create/',
        views.comment_create,
        name='comment_counterparty_create',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_counterparty_edit',
    ),
]

ues/electricity_accounting/urls.py
from django.urls import path

from . import views
from counterparties import views as counterparties_views


app_name = 'accounting'

urlpatterns = [
    path(
        'point_detail/<int:point_id>/meter_create/',
        views.meter_create,
        name='meter_create',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/delete/',
        views.meter_delete,
        name='meter_delete',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/edit/',
        views.meter_edit,
        name='meter_edit',        
    ),
     path(
        'point_detail/<int:point_id>/transformer_create/',
        views.transformer_create,
        name='transformer_create',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/delete/',
        views.transformer_delete,
        name='transformer_delete',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/edit/',
        views.transformer_edit,
        name='transformer_edit',        
    ),
    path(
        'counterparties/contract_detail/<int:contract_id>/point_create/',
        views.point_create,
        name='point_create',
    ),
    path(
        'point_detail/<int:point_id>/',
        views.point_detail,
        name='point_detail',
    ),
    path(
        'point_detail/<int:point_id>/delete/',
        views.point_delete,
        name='point_delete',
    ),
    path(
        'point_detail/<int:point_id>/edit/',
        views.point_edit,
        name='point_edit',
    ),
    path(
        'points_list/',
        views.points_list,
        name='points_list',
    ),
    path(
        'tariff_create/',
        views.tariff_create,
        name='tariff_create',
    ),
    path(
        'tariffs/<int:tariff_id>/delete/',
        views.tariff_delete,
        name='tariff_delete',
    ),
    path(
        'tariffs/<int:tariff_id>/edit/',
        views.tariff_edit,
        name='tariff_edit',
    ),
    path(
        'tariffs_list/',
        views.tariffs_list,
        name='tariffs_list',
    ),
    path(
        'point_detail/<int:point_id>/calculations/add_calculation/',
        views.add_calculation,
        name='add_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/delete/',
        views.del_calculation,
        name='del_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/edit/',
        views.calculation_edit,
        name='calculation_edit',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/update/',
        views.calculation_tariff_update,
        name='calculation_tariff_update',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/download_xlsx_document/',
        views.download_xlsx_document,
        name='download_xlsx_document',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/create/',
        views.interconnection_create,
        name='interconnection_create',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/<int:interconnection_id>/delete/',
        views.interconnection_delete,
        name='interconnection_delete',
    ),
    path(
        'point_detail/<int:point_id>/document/create/',
        views.document_add,
        name='document_add',
    ),
    path(
        'point_detail/<int:point_id>/document/<int:document_id>/delete/',
        views.document_delete,
        name='document_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/create/',
        counterparties_views.comment_create,
        name='comment_point_create',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/delete/',
        counterparties_views.comment_delete,
        name='comment_point_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/edit/',
        counterparties_views.comment_edit,
        name='comment_point_edit',
    ),
    path(
        'static/<int:year>/',
        views.cumulative_statement_of_electricity_consumption,
        name='cumulative_statement_of_electricity_consumption',
    ),
    path(
        'static/<int:year>/download_xlsx_document_yearly_consumptions/',
        views.download_xlsx_document_yearly_consumptions,
        name='download_xlsx_document_yearly_consumptions',
    ),
]

ues/ues/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('accounting/', include('electricity_accounting.urls', namespace='accounting')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('', include('organization.urls', namespace='organization')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

ues/counterparties/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

from .validators import (validate_registration_number,
                         validate_registration_reason_code, 
                         validate_tax_identification_number)


User = get_user_model()


def contract_directory_path(instance, filename):
    return 'contracts/contract_{0}/{1}'.format(instance.contract.title, filename)


class Comment(models.Model):
    """A class model for creating comments on counterparties,
    contracts and accounting points.
    """
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField('Комментарий')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(
        'content_type',
        'object_id',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Коментирии'

    def __str__(self) -> str:
        return self.text[:20]


class Document(models.Model):
    contract = models.ForeignKey(
        'Contract',
        on_delete=models.CASCADE,
        related_name='documents',
    )
    conclusion_date = models.DateField(
        'Дата подписания документа',
        auto_now=False,
        auto_now_add=False,
        null=True,
        blank=True,
    )
    title = models.CharField(
        'Наименование документа',
        max_length=255,
    )
    file = models.FileField(
        upload_to=contract_directory_path,
    )

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
        ordering = ('conclusion_date',)


class Contract(models.Model):
    AGREEMENT_TYPE_CHOICES = [
        ('Contract', 'Контракт'),
        ('Dogovor', 'Договор'),
    ]
    agreement_type = models.CharField(
        'Тип соглашения',
        choices=AGREEMENT_TYPE_CHOICES,
        default='Dogovor',
        help_text='Выбирите тип соглашения из предложенных вариантов.',
        max_length=255,
    )
    comment = GenericRelation(Comment, related_query_name='contract')
    counterparty = models.ForeignKey(
        'Counterparty',
        on_delete=models.CASCADE,
        related_name='contracts',
        verbose_name='Контрагент'
    )
    title = models.CharField(
        'Номер договора',
        max_length=255,
    )
    conclusion_date = models.DateField(
        'Дата заключения договора',
        auto_now=False,
        auto_now_add=False,
        null=True,
        blank=True,
    )
    contract_price = models.PositiveIntegerField(
        'Цена договора',
        blank=True,
        null=True,
    )
    purchase_code = models.CharField(
        'Идентификационный код закупки',
        max_length=255,
        blank=True,
        help_text=(
            'Если договор заключен конкурентным способом, введите'
            ' идентификационный код закупки с сайта https://zakupki.gov.ru'
        ),
    )
    description = models.TextField(
        'Объект закупки',
        help_text='Введите описание работ',
    )
    сompletion_date = models.DateField(
        'Дата завершения работ',
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )
    actual_cost = models.PositiveIntegerField(
        'Фактическая стоимость выполненных работ',
        blank=True,
        null=True,
    )


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Договор'
        verbose_name_plural = 'Договоры'
        ordering = ('conclusion_date',)


class Counterparty(models.Model):
    comment = GenericRelation(Comment, related_query_name='counterparty')
    full_name = models.CharField(
        'Полное наименование',
        max_length=255,
    )
    short_name = models.CharField(
        'Сокращенное наименование',
        max_length=255,
    )
    address = models.CharField(
        'Юридический адрес',
        max_length=200,
    )
    phone_number = models.CharField(
        'Номер телефона',
        blank=True,
        max_length=16,
    )
    email = models.EmailField(
        'Электронный адрес',
        blank=True,
    )
    main_state_registration_number = models.PositiveBigIntegerField(
        'ОГРН',
        db_column='OGRN',
        unique=True,
        help_text='''ОГРН - основной государственный регистрационный номер.
                     ОГРН состоит из 13 арабских цифр.
                     ОГРН индивидуального предпринимателя (ОГРНИП) состоит
                     из 15 арабских цифр.''',
        validators=[validate_registration_number],
    )
    tax_identification_number = models.PositiveBigIntegerField(
        'ИНН',
        db_column='INN',
        unique=True,
        help_text='''ИНН — идентификационный номер налогоплательщика. 
                     ИНН физического лица состоит из 12 арабских цифр. 
                     ИНН юридического лица состоит из 10 арабских цифр.''',
        validators=[validate_tax_identification_number],
    )
    registration_reason_code = models.PositiveIntegerField(
        'КПП',
        db_column='KPP',
        blank=True,
        null=True,
        help_text='''КПП - код причины постановки на учёт.
                     КПП юридического лица состоит из 9 арабских цифр.
                     Индивидуальные предприниматели не имеют КПП
                     (приказ ФНС №ММВ-7-6/435).''',
        validators=[validate_registration_reason_code],
    )
    job_title = models.CharField(
        'Должность руководителя',
        blank=True,
        max_length=200,
    )
    person_full_name = models.CharField(
        'Фамилия, имя и отчество (если есть)',
        max_length=200,
    )

    class Meta:
        ordering = ('full_name',)
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self) -> str:
        return self.short_name

ues/counterparties/forms.py
from django import forms

from .models import Comment, Document ,Contract, Counterparty


class DateInput(forms.DateInput):
    input_type = 'date'
    format = '%d.%m.%Y'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {
          'text': forms.Textarea(attrs={'rows':3, 'cols':5, 'placeholder':'Введите текст комментария',}),
        }
        fields = ('text',)


class DocumentForm(forms.ModelForm):
    conclusion_date = forms.DateField(
        label='Дата заключения договора',
        required=True,
        widget=DateInput({'class': 'form-control'}),
        localize=True,
    )
    class Meta:
        model = Document
        fields = (
            'title',
            'conclusion_date',
            'file',
        )


class ContractForm(forms.ModelForm):
    conclusion_date = forms.DateField(
        label='Дата заключения договора',
        required=True,
        widget=DateInput({'class': 'form-control'}),
        localize=True,
    )
    сompletion_date = forms.DateField(
        label='Дата завершения работ',
        required=False,
        widget=DateInput({'class': 'form-control'}),
        localize=True,
    )

    class Meta:
        model = Contract
        fields = (
            'agreement_type',
            'title',
            'conclusion_date',
            'contract_price',
            'purchase_code',
            'description',
            'сompletion_date',
            'actual_cost',
        )


class CounterpartyForm(forms.ModelForm):
    class Meta:
        model = Counterparty
        fields = (
            'full_name',
            'short_name',
            'address',
            'phone_number',
            'email',
            'main_state_registration_number',
            'tax_identification_number',
            'registration_reason_code',
            'job_title',
            'person_full_name',
        )

ues/templates/counterparties/contract_detail.html
<!-- templates/counterparties/contract_detail.html -->
{% extends 'base.html' %}

{% load user_filters %}
{% load static %}

{% block title %}
  Договор №{{ contract.title }}
{% endblock %}

{% block content %}
<main>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xxl-3 col-xl-12">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            {{ contract.get_agreement_type_display }} №{{ contract.title }}
          </li>
          <li class="list-group-item">
            <a href="{% url 'counterparties:counterparty_detail' contract.counterparty.id %}">
              Контрагент: {{ contract.counterparty.short_name }}
            </a>
          </li>
          <li class="list-group-item">
            Дата заключения: {{ contract.conclusion_date }}
          </li>
          <li class="list-group-item">
            ИКЗ: {{ contract.purchase_code }}
          </li>
          <li class="list-group-item">
            Цена договора: {% if contract.contract_price %} {{ contract.contract_price }} {% endif %}
          </li>
          <li class="list-group-item">
            Объект закупки: {{ contract.description }}
          </li>
          <li class="list-group-item">
            Дата завершения работ: {% if contract.сompletion_date %} {{ contract.сompletion_date }} {% endif %}
          </li>
          <li class="list-group-item">
            Фактическая стоимость выполненных работ: {% if contract.actual_cost %} {{ contract.actual_cost }} {% endif %}</td>
          </li>
          <li class="list-group-item"></li>
        </ul>
        {% if user.is_authenticated %}
          <buttomn>
            <a class="btn btn-primary" href="{% url "counterparties:contract_edit" contract.pk %}">Редактировать договор</a>
            <a class="btn btn-danger" onclick="return confirm('Вы уверены что хотите удалить договор?');" href="{% url 'counterparties:contract_delete' contract.counterparty.pk contract.pk %}">Удалить договор</a>  
          </buttomn>
        {% endif %}
      </div>
      <div class="col">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-doc-tab" data-bs-toggle="tab" data-bs-target="#nav-doc" type="button" role="tab" aria-controls="nav-doc" aria-selected="true">Документы</button>
            <button class="nav-link" id="nav-point-tab" data-bs-toggle="tab" data-bs-target="#nav-point" type="button" role="tab" aria-controls="nav-point" aria-selected="false">Точки учета</button>
            <button class="nav-link" id="nav-comment-tab" data-bs-toggle="tab" data-bs-target="#nav-comment" type="button" role="tab" aria-controls="nav-comment" aria-selected="false">Комментарии</button>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-doc" role="tabpanel" aria-labelledby="nav-doc-tab">
            {% include "counterparties/includes/contract_documents.html" %}
          </div>
          <div class="tab-pane fade" id="nav-point" role="tabpanel" aria-labelledby="nav-point-tab">
            {% if user.is_authenticated %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <buttomn>
                <a class="btn btn-primary me-2" href="{% url 'accounting:point_create' contract.id %}"> Добавить точку учёта электроэнергии</a>
              </buttomn>
            </div>
            {% endif %}
            {% include "accounting/includes/contract_points.html" %}
          </div>
          <div class="tab-pane fade" id="nav-comment" role="tabpanel" aria-labelledby="nav-comment-tab">
            <br>
            {% if user.is_authenticated %}
            <div>
              <form method="post" action="{% url "counterparties:comment_contract_create" contract.id %}">
                <div>
                {% csrf_token %}
                {{ comment_form.text|addclass:"form-control" }}
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Отправить
                  </button>
                </div>
              </form>
            </div>
            {% endif %}
            <div>
              <ul class="list-group list-group-flush">
                {% for comment in comments %}
                  <li class="list-group-item">
                    {{ comment.text }}
                    <br>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                      {{ comment.author.post }} {{ comment.author.last_name }} {{ comment.author.first_name }} {{ comment.created|date:"d.m.Y в H:i" }}
                      {% if user.is_authenticated %}
                        <a class="btn btn-link" href="{% url "counterparties:comment_contract_edit" contract.id comment.id %}" title="Редактировать">
                          <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
                        </a>
                        <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить комментарий?');" href="{% url "counterparties:comment_contract_delete" contract.id comment.id %}" title="Удалить">
                          <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                        </a>
                      {% endif %}
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

ues/templates/counterparties/contracts_list.html
<!-- templates/counterparties/contracts_list.html -->
{% extends 'base.html' %}
{% block title %}
  Список Договор
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src={% static "js/table_sort.js" %}></script>
<div class="container-fluid">
  <table class="table table-striped table-hover table_sort">
    <thead class="table-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Номер договора</th>
        <th scope="col">Наименование Контрагента</th>
        <th scope="col">Дата заключения</th>
        <th scope="col" title="Идентификационный код закупки на сайте https://zakupki.gov.ru/">ИКЗ</th>
        <th scope="col">Цена договора</th>
        <th scope="col">Объект закупки</th>
        <th scope="col">Дата завершения работ</th>
        <th scope="col">Фактическая стоимость выполненных работ</th>
      </tr>
    </thead>
    <tbody>
      {% for contract in page_obj %}
        <tr>
          <td scope="row"></td>
          <td>
           <a href="{% url 'counterparties:contract_detail' contract.id %}">
           {{ contract.title }}
           </a>
          </td>
          <td>
            <a href="{% url 'counterparties:counterparty_detail' contract.counterparty.id %}">
            {{ contract.counterparty.short_name }}
          </td>
          <td>{{ contract.conclusion_date }}</td>
          <td>{{ contract.purchase_code }}</td>
          <td>{% if contract.contract_price %}{{ contract.contract_price }}{% endif %}</td>
          <td>{{ contract.description }}</td>
          <td>{% if contract.сompletion_date %}{{ contract.сompletion_date }} {% endif %}</td>
          <td>{% if contract.actual_cost %}{{ contract.actual_cost }}{% endif %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% include 'includes/paginator.html' %}
{% endblock %} 

ues/templates/counterparties/counterperty_detail.html
<!-- templates/counterparties/counterparty_detail.html -->
{% extends 'base.html' %}

{% block title %}
  {{ counterparty.short_name }}
{% endblock title %}

{% load user_filters %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
  <script src="{% static 'js/table_sort.js' %}"></script>
  <main>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xxl-3 col-xl-12">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Полное наименование: {{ counterparty.full_name }}
            </li>
            <li class="list-group-item">
              Сокращенное наименование: {{ counterparty.short_name }}
            </li>
            <li class="list-group-item">
              Юридический адрес: {{ counterparty.address }}
            </li>
            <li class="list-group-item">
              ОГРН: {{ counterparty.main_state_registration_number }}
            </li>
            <li class="list-group-item">
              ИНН: {{ counterparty.tax_identification_number }}
            </li>
            <li class="list-group-item">
              КПП: {% if counterparty.registration_reason_code %}{{ counterparty.registration_reason_code }}{% endif %}
            </li>
            <li class="list-group-item">
              Контактный телефон: {{ counterparty.phone_number }}
            </li>
            <li class="list-group-item">
              Электронная почта: {{ counterparty.email }}
            </li>
            <li class="list-group-item">
              Руководитель организации:
              {{ counterparty.job_title }}
              {{ counterparty.person_full_name }}
            </li>
            <li class="list-group-item"></li>
          </ul>
          {% if user.is_authenticated %}
            <buttomn>
              <a class="btn btn-primary" href="{% url "counterparties:counterparty_edit" counterparty.pk %}">Редактировать контрагента</a>
              <a class="btn btn-danger" onclick="return confirm('Вы уверены что хотите удалить контрагента?');" href="{% url "counterparties:counterparty_delete" counterparty.pk %}">Удалить контрагента</a>
            </buttomn>
          {% endif %}
        </div>
        <div class="col">
          <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
              <button class="nav-link active" id="nav-docs-tab" data-bs-toggle="tab" data-bs-target="#nav-docs" type="button" role="tab" aria-controls="nav-docs" aria-selected="true">Договоры</button>
              <button class="nav-link" id="nav-point-tab" data-bs-toggle="tab" data-bs-target="#nav-point" type="button" role="tab" aria-controls="nav-point" aria-selected="false">Точки учета</button>
              <button class="nav-link" id="nav-comment-tab" data-bs-toggle="tab" data-bs-target="#nav-comment" type="button" role="tab" aria-controls="nav-comment" aria-selected="false">Комментарии</button>
              {% if user.is_authenticated %}
                <buttomn>
                  <a class="btn btn-primary me-2" href="{% url "counterparties:contract_create" counterparty.pk %}"> Добавить договор</a>
                </buttomn>
              {% endif %}
            </div>
          </nav>
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-docs" role="tabpanel" aria-labelledby="nav-docs-tab">
              {% if contracts %}
                <table class="table caption-top table-striped table-hover table_sort">
                  <caption>Всего договоров: {{ contracts_count }}</caption>
                  <thead class="table-dark">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Номер договора</th>
                      <th scope="col">Дата заключения</th>
                      <th scope="col" title= "Идентификационный код закупки на сайте https://zakupki.gov.ru/">ИКЗ</th>
                      <th scope="col">Цена договора</th>
                      <th scope="col">Объект закупки</th>
                      <th scope="col">Дата завершения работ</th>
                      <th scope="col">Фактическая стоимость работ</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for contract in contracts %}
                      <tr>
                        <td scope="row"></td>
                        <td>
                         <a href="{% url "counterparties:contract_detail" contract.id %}">
                         {{ contract.title }}
                         </a>
                        </td>
                        <td>{{ contract.conclusion_date }}</td>
                        <td>{{ contract.purchase_code }}</td>
                        <td>{% if contract.contract_price %} {{ contract.contract_price }} {% endif %}</td>
                        <td>{{ contract.description }}</td>
                        <td>{% if contract.сompletion_date %}{{ contract.сompletion_date }} {% endif %}</td>
                        <td> {% if contract.actual_cost %}{{ contract.actual_cost }}{% endif %}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              {% endif %}
            </div>
            <div class="tab-pane fade" id="nav-point" role="tabpanel" aria-labelledby="nav-point-tab">
              {% include "accounting/includes/contract_points.html" %}
            </div>
            <div class="tab-pane fade" id="nav-comment" role="tabpanel" aria-labelledby="nav-comment-tab">
              <br>
              {% if user.is_authenticated %}
              <div>
                <form method="post" action="{% url "counterparties:comment_counterparty_create" counterparty.id %}">
                  <div>
                  {% csrf_token %}
                  {{ comment_form.text|addclass:"form-control" }}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Отправить
                    </button>
                  </div>
                </form>
              </div>
              {% endif %}
              <div>
                <ul class="list-group list-group-flush">
                  {% for comment in comments %}
                    <li class="list-group-item">
                      {{ comment.text }}
                      <br>
                      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        {{ comment.author.post }} {{ comment.author.last_name }} {{ comment.author.first_name }} {{ comment.created|date:"d.m.Y в H:i" }}
                        {% if user.is_authenticated %}
                          <a class="btn btn-link" href="{% url "counterparties:comment_counterparty_edit" counterparty.id comment.id %}" title="Редактировать">
                            <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
                          </a>
                          <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить комментарий?');" href="{% url "counterparties:comment_counterparty_delete" counterparty.id comment.id %}" title="Удалить">
                            <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                          </a>
                        {% endif %}
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              </div> 
            </div>
          </div>
        </div> 
      </div>
    </div>
  </main>
{% endblock content %}