ues/counterparties/urls.py
from django.urls import path

from . import views


app_name = 'counterparties'

urlpatterns = [
    path(
        'contract_detail/<int:contract_id>/document_create/',
        views.add_document,
        name='add_document',
    ),
    path(
        'contract_detail/<int:contract_id>/document/<int:document_id>/delete/',
        views.delete_document,
        name='delete_document',
    ),
    path(
        '<int:counterparty_id>/contract_create/',
        views.contract_create,
        name='contract_create'
    ),
    path(
        '<int:counterparty_id>/contract_detail/<int:contract_id>/delete/',
        views.contract_delete,
        name='contract_delete'
    ),
    path(
        'contract_detail/<int:contract_id>/',
        views.contract_detail,
        name='contract_detail'
    ),
    path(
        'contract_detail/<int:contract_id>/edit/',
        views.contract_edit,
        name='contract_edit'
    ),
    path(
        'contracts_list/',
        views.contracts_list,
        name='contracts_list',
    ),
    path(
        'create/',
        views.counterparty_create,
        name='counterparty_create',
    ),
    path(
        '<int:counterparty_id>/delete/',
        views.counterparty_delete,
        name='counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/',
        views.counterparty_detail,
        name='counterparty_detail',
    ),
    path(
        '<int:counterparty_id>/edit/',
        views.counterparty_edit,
        name='counterparty_edit',
    ),
    path(
        'counterparties_list/',
        views.counterparties_list,
        name='counterparties_list'
    ),
    path(
        'contract_detail/<int:contract_id>/comments/create/',
        views.comment_create,
        name='comment_contract_create',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_contract_delete',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_contract_edit',
    ),
    path(
        '<int:counterparty_id>/comments/create/',
        views.comment_create,
        name='comment_counterparty_create',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_counterparty_edit',
    ),
]

ues/organization/urls.py
from django.urls import path

from . import views


app_name = 'organization'

urlpatterns = [
    path(
        'organization_create/',
        views.organization_create,
        name='organization_create',
    ),
    path(
        'organization_detail/<int:organization_id>/delete/',
        views.organization_delete,
        name='organization_delete',
    ),
    path(
        'organization_detail/<int:organization_id>/edit/',
        views.organization_edit,
        name='organization_edit',
    ),
    path(
        'organization/',
        views.organization_detail,
        name='organization_detail',
    ),
    path(
        '',
        views.IndexView.as_view(),
        name='about_organization',
    ),
]

ues/ues/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('accounting/', include('electricity_accounting.urls', namespace='accounting')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('', include('organization.urls', namespace='organization')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

ues/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView,
                                       )                                       
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login',
         ),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout',
         ),
    path('password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done',
        ),
    path('password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change_form',
        ),
#    path("reset/done/",
#        PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
#        name="password_reset_complete",
#        ),
#    path("reset/<uidb64>/<token>",
#        PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
#        name="password_reset_confirm",
#        ),
#    path("password_reset/done/",
#        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
#        name="password_reset_done",
#        ),
#    path("password_reset/",
#        PasswordResetView.as_view(template_name="users/password_reset_form.html"),
#        name="password_reset_form",
#        ),
    path(
        'users/list/',
        views.users_list,
        name='users_list',  
    ),
    path(
        'users/profile/edit',
        views.user_edit,
        name='user_edit',
    ),
    path(
        'users/profile/<int:user_id>/',
        views.user_profile,
        name='user_profile',
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

ues/templates/includes/documents.html
<!-- templates/counterparties/includes/contract_documents.html -->
{% load user_filters %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src="{% static 'js/table_sort.js' %}"></script>
<table class="table caption-top table-striped table-hover table_sort">
  <caption>Всего документов загружено: {{ documents_count }}</caption>
  <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование документа</th>
      <th scope="col">Дата подписания</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% if user.is_authenticated %}
      <form method="post" enctype="multipart/form-data" action="{% url 'counterparties:add_document' contract.id %}">
        {% csrf_token %}
        <tr>
          <td></td>
          <td>{{ form.title|addclass:"form-control" }}</td>
          <td>{{ form.conclusion_date|addclass:"form-control" }}</td>
          <td>{{ form.file|addclass:"form-control" }}</td>
          <td>
            <button type="submit" class="btn btn-link" title="Загрузить документ">
              <img src="{% static "icons/upload.svg " %}" alt="Bootstrap" width="16" height="16">
            </button>
          </td>
        </tr>
      </form>
    {% endif %}
    {% for document in documents %}
      <tr>
        <td scope="row"></td>
        <td>{{ document.title }}</td>
        <td>{{ document.conclusion_date }}</td>
        <td>
          <a class="btn btn-link" href="{{ document.file.url}}" title="Скачать документ" download>
            <img src="{% static "icons/download.svg " %}" alt="Bootstrap" width="16" height="16">
          </a>
        </td>
        {% if user.is_authenticated %}
          <td>
            <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить {{ document.title }}?');" href="{% url 'counterparties:delete_document' contract.id document.id %}" title="Удалить доумент">
              <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
            </a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

ues/templates/includes/footer.html
<!-- templates/includes/footer.html -->
{% load static %}
<div class="container-fluid">
  <div class="row">
    <div class="footer-text text-center">
      <img src="{% static 'img/fav/android-chrome-256x256.png' %}" width="20" height="20" class="d-inline-block align-top" alt="">
      <span style="color:blue">ООО "УЭС"</span>
      <br>© {% now "Y" %} Все права защищены
    </div>
  </div>
</div>

ues/templates/includes/header.html
<!-- templates/includes/header.html -->
{% load static %}
{% load thumbnail %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "counterparties:counterparties_list" %}">
      <img src="{% static 'img/logo.png' %}" width="82" height="40" class="d-inline-block align-top" alt="" title="Общество с ограниченной ответственностью УЭС">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav nav-underline me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if view_name  == 'counterparties:counterparties_list' or view_name  == 'counterparties:contracts_list' or view_name  == 'counterparties:counterparty_create'%}active{% endif %}" href="{% url 'counterparties:counterparties_list' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Контрагенты
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item {% if view_name  == 'counterparties:counterparties_list' %}active{% endif %}" href="{% url 'counterparties:counterparties_list' %}">Контрагенты</a></li>
            <li><a class="dropdown-item {% if view_name  == 'counterparties:contracts_list' %}active{% endif %}" href="{% url 'counterparties:contracts_list' %}">Договоры</a></li>
            {% if user.is_authenticated %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item {% if view_name  == 'counterparties:counterparty_create' %}active{% endif %}" href="{% url 'counterparties:counterparty_create' %}">Добавить контрагента</a></li>
            {% endif %}          
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if view_name  == 'accounting:points_list' or view_name  == 'accounting:tariffs_list' or view_name  == 'accounting:cumulative_statement_of_electricity_consumption' %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Учёт электроэнергии
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item {% if view_name == "accounting:points_list" %}active{% endif %}" href="{% url "accounting:points_list" %}">Точки учета</a></li>
            <li><a class="dropdown-item {% if view_name == "accounting:tariffs_list" %}active{% endif %}" href="{% url "accounting:tariffs_list" %}">Тарифы</a></li>
            <li><a class="dropdown-item {% if view_name == "accounting:cumulative_statement_of_electricity_consumption" %}active{% endif %}" href="{% url 'accounting:cumulative_statement_of_electricity_consumption' year %}">Статистика</a></li>
            {% if user.is_authenticated %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item {% if view_name == "accounting:tariff_create" %}active{% endif %}" href="{% url "accounting:tariff_create" %}">Добавить тариф</a></li>
            {% endif %}
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle {% if view_name  == 'users:users_list' or view_name  == 'organization:organization_detail' %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Наша организация
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item {% if view_name  == 'users:users_list'%}active{% endif %}" href="{% url 'users:users_list' %}">Наши сотрудники</a></li>
            <li><a class="dropdown-item {% if view_name  == 'organization:organization_detail'%}active{% endif %}" href="{% url 'organization:organization_detail'%}">Реквизиты</a></li>
            <li><a class="dropdown-item" href="{% url 'organization:about_organization'%}">О нас</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <div class="container-fluid">
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
      <button class="btn btn-outline-success me-2" type="submit">Поиск</button>
    </form>
    <div class="dropdown-center"> Пользователь:
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        {{ user.first_name }}
        {% thumbnail user.photo "25x25" crop="center" upscale=True as im %}
          <img class="img-fluid rounded-circle" src="{{ im.url }}">
        {% endthumbnail %}
      </button>
      <ul class="dropdown-menu dropdown-menu-end">
        {% with request.resolver_match.view_name as view_name %}
          {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:user_profile' user.id %}">Профиль</a></li>
            <li><a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
          {% else %}
            <li> 
              <a class="dropdown-item {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li>
              <a class="dropdown-item {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>
{% endwith %} 

ues/templates/includes/paginator.html
<!-- templates/includes/paginator.html -->

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}