ues/counterparties/urls.py
from django.urls import path

from . import views


app_name = 'counterparties'

urlpatterns = [
    path(
        'contract_detail/<int:contract_id>/document_create/',
        views.add_document,
        name='add_document',
    ),
    path(
        'contract_detail/<int:contract_id>/document/<int:document_id>/delete/',
        views.delete_document,
        name='delete_document',
    ),
    path(
        '<int:counterparty_id>/contract_create/',
        views.contract_create,
        name='contract_create'
    ),
    path(
        '<int:counterparty_id>/contract_detail/<int:contract_id>/delete/',
        views.contract_delete,
        name='contract_delete'
    ),
    path(
        'contract_detail/<int:contract_id>/',
        views.contract_detail,
        name='contract_detail'
    ),
    path(
        'contract_detail/<int:contract_id>/edit/',
        views.contract_edit,
        name='contract_edit'
    ),
    path(
        'contracts_list/',
        views.contracts_list,
        name='contracts_list',
    ),
    path(
        'create/',
        views.counterparty_create,
        name='counterparty_create',
    ),
    path(
        '<int:counterparty_id>/delete/',
        views.counterparty_delete,
        name='counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/',
        views.counterparty_detail,
        name='counterparty_detail',
    ),
    path(
        '<int:counterparty_id>/edit/',
        views.counterparty_edit,
        name='counterparty_edit',
    ),
    path(
        'counterparties_list/',
        views.counterparties_list,
        name='counterparties_list'
    ),
    path(
        'contract_detail/<int:contract_id>/comments/create/',
        views.comment_create,
        name='comment_contract_create',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_contract_delete',
    ),
    path(
        'contract_detail/<int:contract_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_contract_edit',
    ),
    path(
        '<int:counterparty_id>/comments/create/',
        views.comment_create,
        name='comment_counterparty_create',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/delete/',
        views.comment_delete,
        name='comment_counterparty_delete',
    ),
    path(
        '<int:counterparty_id>/comments/<int:comment_id>/edit/',
        views.comment_edit,
        name='comment_counterparty_edit',
    ),
]

ues/electricity_accounting/urls.py
from django.urls import path

from . import views
from counterparties import views as counterparties_views


app_name = 'accounting'

urlpatterns = [
    path(
        'point_detail/<int:point_id>/meter_create/',
        views.meter_create,
        name='meter_create',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/delete/',
        views.meter_delete,
        name='meter_delete',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/edit/',
        views.meter_edit,
        name='meter_edit',        
    ),
     path(
        'point_detail/<int:point_id>/transformer_create/',
        views.transformer_create,
        name='transformer_create',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/delete/',
        views.transformer_delete,
        name='transformer_delete',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/edit/',
        views.transformer_edit,
        name='transformer_edit',        
    ),
    path(
        'counterparties/contract_detail/<int:contract_id>/point_create/',
        views.point_create,
        name='point_create',
    ),
    path(
        'point_detail/<int:point_id>/',
        views.point_detail,
        name='point_detail',
    ),
    path(
        'point_detail/<int:point_id>/delete/',
        views.point_delete,
        name='point_delete',
    ),
    path(
        'point_detail/<int:point_id>/edit/',
        views.point_edit,
        name='point_edit',
    ),
    path(
        'points_list/',
        views.points_list,
        name='points_list',
    ),
    path(
        'tariff_create/',
        views.tariff_create,
        name='tariff_create',
    ),
    path(
        'tariffs/<int:tariff_id>/delete/',
        views.tariff_delete,
        name='tariff_delete',
    ),
    path(
        'tariffs/<int:tariff_id>/edit/',
        views.tariff_edit,
        name='tariff_edit',
    ),
    path(
        'tariffs_list/',
        views.tariffs_list,
        name='tariffs_list',
    ),
    path(
        'point_detail/<int:point_id>/calculations/add_calculation/',
        views.add_calculation,
        name='add_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/delete/',
        views.del_calculation,
        name='del_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/edit/',
        views.calculation_edit,
        name='calculation_edit',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/update/',
        views.calculation_tariff_update,
        name='calculation_tariff_update',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/download_xlsx_document/',
        views.download_xlsx_document,
        name='download_xlsx_document',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/create/',
        views.interconnection_create,
        name='interconnection_create',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/<int:interconnection_id>/delete/',
        views.interconnection_delete,
        name='interconnection_delete',
    ),
    path(
        'point_detail/<int:point_id>/document/create/',
        views.document_add,
        name='document_add',
    ),
    path(
        'point_detail/<int:point_id>/document/<int:document_id>/delete/',
        views.document_delete,
        name='document_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/create/',
        counterparties_views.comment_create,
        name='comment_point_create',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/delete/',
        counterparties_views.comment_delete,
        name='comment_point_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/edit/',
        counterparties_views.comment_edit,
        name='comment_point_edit',
    ),
    path(
        'static/<int:year>/',
        views.cumulative_statement_of_electricity_consumption,
        name='cumulative_statement_of_electricity_consumption',
    ),
    path(
        'static/<int:year>/download_xlsx_document_yearly_consumptions/',
        views.download_xlsx_document_yearly_consumptions,
        name='download_xlsx_document_yearly_consumptions',
    ),
]

ues/ues/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('accounting/', include('electricity_accounting.urls', namespace='accounting')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('counterparties/', include('counterparties.urls', namespace='counterparties')),
    path('', include('organization.urls', namespace='organization')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

ues/counterparties/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

from .validators import (validate_registration_number,
                         validate_registration_reason_code, 
                         validate_tax_identification_number)


User = get_user_model()


def contract_directory_path(instance, filename):
    return 'contracts/contract_{0}/{1}'.format(instance.contract.title, filename)


class Comment(models.Model):
    """A class model for creating comments on counterparties,
    contracts and accounting points.
    """
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField('Комментарий')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(
        'content_type',
        'object_id',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Коментирии'

    def __str__(self) -> str:
        return self.text[:20]


class Document(models.Model):
    contract = models.ForeignKey(
        'Contract',
        on_delete=models.CASCADE,
        related_name='documents',
    )
    conclusion_date = models.DateField(
        'Дата подписания документа',
        auto_now=False,
        auto_now_add=False,
        null=True,
        blank=True,
    )
    title = models.CharField(
        'Наименование документа',
        max_length=255,
    )
    file = models.FileField(
        upload_to=contract_directory_path,
    )

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
        ordering = ('conclusion_date',)


class Contract(models.Model):
    AGREEMENT_TYPE_CHOICES = [
        ('Contract', 'Контракт'),
        ('Dogovor', 'Договор'),
    ]
    agreement_type = models.CharField(
        'Тип соглашения',
        choices=AGREEMENT_TYPE_CHOICES,
        default='Dogovor',
        help_text='Выбирите тип соглашения из предложенных вариантов.',
        max_length=255,
    )
    comment = GenericRelation(Comment, related_query_name='contract')
    counterparty = models.ForeignKey(
        'Counterparty',
        on_delete=models.CASCADE,
        related_name='contracts',
        verbose_name='Контрагент'
    )
    title = models.CharField(
        'Номер договора',
        max_length=255,
    )
    conclusion_date = models.DateField(
        'Дата заключения договора',
        auto_now=False,
        auto_now_add=False,
        null=True,
        blank=True,
    )
    contract_price = models.PositiveIntegerField(
        'Цена договора',
        blank=True,
        null=True,
    )
    purchase_code = models.CharField(
        'Идентификационный код закупки',
        max_length=255,
        blank=True,
        help_text=(
            'Если договор заключен конкурентным способом, введите'
            ' идентификационный код закупки с сайта https://zakupki.gov.ru'
        ),
    )
    description = models.TextField(
        'Объект закупки',
        help_text='Введите описание работ',
    )
    сompletion_date = models.DateField(
        'Дата завершения работ',
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )
    actual_cost = models.PositiveIntegerField(
        'Фактическая стоимость выполненных работ',
        blank=True,
        null=True,
    )


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Договор'
        verbose_name_plural = 'Договоры'
        ordering = ('conclusion_date',)


class Counterparty(models.Model):
    comment = GenericRelation(Comment, related_query_name='counterparty')
    full_name = models.CharField(
        'Полное наименование',
        max_length=255,
    )
    short_name = models.CharField(
        'Сокращенное наименование',
        max_length=255,
    )
    address = models.CharField(
        'Юридический адрес',
        max_length=200,
    )
    phone_number = models.CharField(
        'Номер телефона',
        blank=True,
        max_length=16,
    )
    email = models.EmailField(
        'Электронный адрес',
        blank=True,
    )
    main_state_registration_number = models.PositiveBigIntegerField(
        'ОГРН',
        db_column='OGRN',
        unique=True,
        help_text='''ОГРН - основной государственный регистрационный номер.
                     ОГРН состоит из 13 арабских цифр.
                     ОГРН индивидуального предпринимателя (ОГРНИП) состоит
                     из 15 арабских цифр.''',
        validators=[validate_registration_number],
    )
    tax_identification_number = models.PositiveBigIntegerField(
        'ИНН',
        db_column='INN',
        unique=True,
        help_text='''ИНН — идентификационный номер налогоплательщика. 
                     ИНН физического лица состоит из 12 арабских цифр. 
                     ИНН юридического лица состоит из 10 арабских цифр.''',
        validators=[validate_tax_identification_number],
    )
    registration_reason_code = models.PositiveIntegerField(
        'КПП',
        db_column='KPP',
        blank=True,
        null=True,
        help_text='''КПП - код причины постановки на учёт.
                     КПП юридического лица состоит из 9 арабских цифр.
                     Индивидуальные предприниматели не имеют КПП
                     (приказ ФНС №ММВ-7-6/435).''',
        validators=[validate_registration_reason_code],
    )
    job_title = models.CharField(
        'Должность руководителя',
        blank=True,
        max_length=200,
    )
    person_full_name = models.CharField(
        'Фамилия, имя и отчество (если есть)',
        max_length=200,
    )

    class Meta:
        ordering = ('full_name',)
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self) -> str:
        return self.short_name

ues/templates/accounting/calculation_edit.html
<!-- templates/accounting/calculation_edit.html -->
{% extends 'base.html' %}

{% block title %}
  Редактировать показания электросчётчика
{% endblock title %}

{% block content %}

  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Редактировать показания электросчётчика
          </div>

          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %}
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}>
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                    {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить изменения
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ues/templates/accounting/point_detail.html
<!-- templates/accounting/point_detail.html -->

{% extends 'base.html' %}

{% load thumbnail %}
{% load user_filters %}
{% load static %}

{% block title %}Точка учёта: {{ point.name }} {% endblock %}
{% block content %}
<main>
  {% if alert_flag %}
    <script>alert("Перед внесением показаний обязательно добавте активный счётчик электроэнергии")</script>  
  {% endif %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-xxl-3 col-xl-12">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <a href="{% url 'counterparties:counterparty_detail' point.contract.counterparty.id %}">
              Контрагент: {{ point.contract.counterparty.short_name }}
            </a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'counterparties:contract_detail' point.contract.id %}">
              {{ point.contract.get_agreement_type_display }} №{{ point.contract.title }}
            </a>
          </li>
          <li class="list-group-item">
            Дата заключения: {{ point.contract.conclusion_date }}
          </li>
          <li class="list-group-item">
            ИКЗ: {{ point.contract.purchase_code }}
          </li>
          <li class="list-group-item">
            Цена договора: {% if point.contract.contract_price%}{{ point.contract.contract_price }}{% endif %}
          </li>
          <li class="list-group-item">
            Объект закупки: {{ point.contract.description }}
          </li>
          <li class="list-group-item"><b>Наименование точки учёта:</b> {{ point.name }} </li>
          <li class="list-group-item"><b>Место расположение точки учета:</b> {{ point.location }}</li>
          <li class="list-group-item"><b>Источник питания:</b> {{ point.power_supply }}</li>
          <li class="list-group-item"><b>Тип учёта:</b> {{ point.get_type_of_accounting_display }}</li>
          <li class="list-group-item"><b>Тариф:</b> {{ point.get_tariff_display }}</li>
          <li class="list-group-item"><b>Наценка:</b> {{ point.margin }} руб./кВт*ч</li>
          <li class="list-group-item"><b>Потери в линиях:</b> {{ point.losses }}%</li>
          <li class="list-group-item"><b>Постоянные потери в трансформаторе:</b> {{ point.constant_losses }} кВт*ч</li>
          <li class="list-group-item"><b>Коэффициент трансформации:</b> {{ point.transformation_coefficient }}</li>
        </ul>
        {% if user.is_authenticated %}
          <buttomn>
            <a class="btn btn-primary" href="{% url "accounting:point_edit" point.id %}">Редактировать точку учета</a>
            <a class="btn btn-danger" onclick="return confirm('Вы уверены что хотите удалить точку учета {{ point.name }}?');" href="{% url "accounting:point_delete" point.id %}">Удалить точку учета</a>  
          </buttomn>
        {% endif %}
      </div>
      <div class="col">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link" id="nav-devices-tab" data-bs-toggle="tab" data-bs-target="#nav-devices" type="button" role="tab" aria-controls="nav-devices" aria-selected="true">Приборы учета</button>
            <button class="nav-link active" id="nav-indications-tab" data-bs-toggle="tab" data-bs-target="#nav-indications" type="button" role="tab" aria-controls="nav-indications" aria-selected="false">Показания</button>
            <button class="nav-link" id="nav-interconnection-tab" data-bs-toggle="tab" data-bs-target="#nav-interconnection" type="button" role="tab" aria-controls="nav-interconnection" aria-selected="false">Взаимосвязи</button>
            <button class="nav-link" id="nav-doc-tab" data-bs-toggle="tab" data-bs-target="#nav-doc" type="button" role="tab" aria-controls="nav-doc" aria-selected="false">Документация</button>
            <button class="nav-link" id="nav-comment-tab" data-bs-toggle="tab" data-bs-target="#nav-comment" type="button" role="tab" aria-controls="nav-comment" aria-selected="false">Комментарии</button>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade" id="nav-devices" role="tabpanel" aria-labelledby="nav-devices-tab">
            {% if user.is_authenticated %}
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <buttomn>
                  <a class="btn btn-primary me-2" href="{% url 'accounting:meter_create' point.id %}"> Добавить счётчик электроэнергии</a>
                </buttomn>
                <buttomn>
                  <a class="btn btn-primary me-2" href="{% url 'accounting:transformer_create' point.id %}"> Добавить трансформатор тока</a>
                </buttomn>
              </div>
            {% endif %}
            <br>
            {% include "accounting/includes/meters_list.html" %}
            {% include "accounting/includes/transformers_list.html" %}
          </div>
          <div class="tab-pane fade show active" id="nav-indications" role="tabpanel" aria-labelledby="nav-indications-tab">
            {% include "accounting/includes/calculations_list.html" %}
          </div>
          <div class="tab-pane fade" id="nav-interconnection" role="tabpanel" aria-labelledby="nav-interconnection-tab">
            {% if user.is_authenticated %}
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <buttomn>
                  <a class="btn btn-primary me-2" href="{% url 'accounting:interconnection_create' point.id %}"> Добавить взаимосвязь</a>
                </buttomn>
              </div>
            {% endif %}
            {% include "accounting/includes/interconnection_list.html" %}
          </div>
          <div class="tab-pane fade" id="nav-doc" role="tabpanel" aria-labelledby="nav-doc-tab">
            {% include "accounting/includes/point_documents.html" %}
          </div>
          <div class="tab-pane fade" id="nav-comment" role="tabpanel" aria-labelledby="nav-comment-tab">
            <br>
            {% if user.is_authenticated %}
            <div>
              <form method="post" action="{% url "accounting:comment_point_create" point.id %}">
                <div>
                {% csrf_token %}
                {{ comment_form.text|addclass:"form-control" }}
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Отправить
                  </button>
                </div>
              </form>
            </div>
            {% endif %}
            <div>
              <ul class="list-group list-group-flush">
                {% for comment in comments %}
                  <li class="list-group-item">
                    {{ comment.text }}
                    <br>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                      {{ comment.author.post }} {{ comment.author.last_name }} {{ comment.author.first_name }} {{ comment.created|date:"d.m.Y в H:i" }}
                      {% if user.is_authenticated %}
                        <a class="btn btn-link" href="{% url "accounting:comment_point_edit" point.id comment.id %}" title="Редактировать">
                          <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
                        </a>
                        <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить комментарий?');" href="{% url "accounting:comment_point_delete" point.id comment.id %}" title="Удалить">
                          <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
                        </a>
                      {% endif %}
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

ues/templates/accounting/points_list.html
<!-- templates/accounting/points_list.html -->
{% extends 'base.html' %}
{% block title %}
  Список Точек учёта
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src={% static "js/table_sort.js" %}></script>
<div class="container-fluid">
  <table class="table table-striped table-hover table_sort">
    <thead class="table-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Контрагент</th>
        <th scope="col">Наименование точки учёта</th>
        <th scope="col">Место расположения точки учета</th>
        <th scope="col">Источник питания</th>
        <th scope="col">Тип учёта</th>
      </tr>
    </thead>
    <tbody>
      {% for point in page_obj %}
        <tr>
          <td scope="row"></td>
          <td>
            <a href="{% url 'counterparties:counterparty_detail' point.contract.counterparty.id %}">
              {{ point.contract.counterparty.short_name }}</td>
            </a>
          <td>
            <a href="{% url 'accounting:point_detail' point.id %}">
              {{ point.name }}
            </a>
          </td>
          <td>{{ point.location }}</td>
          <td>{{ point.power_supply }}</td>
          <td>{{ point.get_type_of_accounting_display }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% include 'includes/paginator.html' %}
{% endblock %} 

ues/templates/accounting/tariffs_list.html
<!-- templates/accounting/tariffs_list.html -->
{% extends 'base.html' %}
{% block title %}
  Тарифы
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/table_sort.css' %}">
<script src={% static "js/table_sort.js" %}></script>
<div class="container-fluid">
  <table class="table table-striped table-hover table_sort">
    <thead class="table-dark">
      <tr>
        <th class="align-middle" scope="col">#</th>
        <th class="align-middle" scope="col">Период действия тарифа</th>
        <th class="align-middle" scope="col" title="Тариф для потребителей с уровнем напряжения ВН, рассчитывающихся по I ценовой категории, руб./кВтч">ВН</th>
        <th class="align-middle" scope="col" title="Тариф для потребителей с уровнем напряжения СН-I, рассчитывающихся по I ценовой категории, руб./кВтч">СН-I</th>
        <th class="align-middle" scope="col" title="Тариф для потребителей с уровнем напряжения СН-II, рассчитывающихся по I ценовой категории, руб./кВтч">СН-II</th>
        <th class="align-middle" scope="col" title="Тариф для потребителей с уровнем напряжения НН, рассчитывающихся по I ценовой категории, руб./кВтч">НН</th>
        <th class="align-middle" scope="col"></th>
        <th class="align-middle" scope="col" title="Тариф для городского населения с однотирфным прибором учета. Для первого диапазона объемов потребления (до 10980 кВт*ч), Для второго диапазона объемов потребления (от 10980 – 14640 кВт*ч) и Для третьего диапазона объемов потребления (свыше 14640 кВт*ч), руб./кВтч">
          Городское<br>население
        </th>
        <th class="align-middle" scope="col" title="Тариф для сельского населения с однотирфным прибором учета. Для первого диапазона объемов потребления (до 10980 кВт*ч), Для второго диапазона объемов потребления (от 10980 – 14640 кВт*ч) и Для третьего диапазона объемов потребления (свыше 14640 кВт*ч), руб./кВтч">
          Сельское<br>население
        </th>
        {% if user.is_authenticated %}
          <th class="align-middle" scope="col"></th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for tariff in page_obj %}
        <tr>
          <td scope="row" class="align-middle"></td>
          <td class="align-middle">
            {{ tariff.begin_tariff_period}} - {{ tariff.end_tariff_period}}
          <td class="align-middle">{{ tariff.high_voltage_tariff}}</td>
          <td class="align-middle">{{ tariff.medium_voltage_tariff_1 }}</td>
          <td class="align-middle">{{ tariff.medium_voltage_tariff_2 }}</td>
          <td class="align-middle">{{ tariff.low_voltage_tariff }}</td>
          <td>
            Для первого диапазона объемов потребления (до 10980 кВт*ч)
            <br>
            Для второго диапазона объемов потребления (от 10980 – 14640 кВт*ч)
            <br>
            Для третьего диапазона объемов потребления (свыше 14640 кВт*ч)
          </td>
          <td class="align-middle">
            {{ tariff.urban_tariff_1 }}
            <br>
            {{ tariff.urban_tariff_2 }}
            <br>
            {{ tariff.urban_tariff_3 }}
          </td>
          <td class="align-middle">
            {{ tariff.rural_tariff_1 }}
            <br>
            {{ tariff.rural_tariff_2 }}
            <br>
            {{ tariff.rural_tariff_3 }}
          </td>
          {% if user.is_authenticated %}
            <td class="align-middle">
              <a class="btn btn-link" href="{% url "accounting:tariff_edit" tariff.id %}" title="Редактировать">
                <img src="{% static "icons/pencil-square.svg " %}" alt="Bootstrap" width="16" height="16">
              </a>
              <a class="btn btn-link" onclick="return confirm('Вы уверены что хотите удалить тариф?');" href="{% url 'accounting:tariff_delete' tariff.id %}" title="Удалить">
                <img src="{% static "icons/trash.svg " %}" alt="Bootstrap" width="16" height="16">
              </a>
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% include 'includes/paginator.html' %}
{% endblock %} 